#!/usr/bin/env python3
# Generated by OpenAI GPT-5.4 extended thinking

"""Build intermediate JSONL and MQA datasets from scenario/answer/evaluation JSON files.

This script assumes three progressively enriched JSON files that share the same `idx` field:
- scenario.json: base scenario/question/rules
- answer.json: scenario + answer
- evaluation.json: scenario + answer + score + reason

Outputs:
1. unified_intermediate.jsonl
2. mqa_rule_choice.jsonl
3. mqa_score_band.jsonl
4. manifest.json
5. difficulty-specific splits under task-specific subdirectories

The script is intentionally deterministic so later experiments are reproducible.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

# This script is for the use of generating usable dataset from c-varc.jsonl for our fituning-project.

SCHEMA_VERSION = "mqa-v1"
RULE_CHOICE_OPTIONS = ["A", "B", "C", "D"] # every question is binded with 4 answers
SCORE_BAND_OPTIONS = ["A", "B", "C", "D", "E"] # decided upon the score of each question


def load_items(path: str) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """从JSON文件加载数据项并返回项目列表和元数据字典
    
    Args:
        path: JSON文件的路径
        
    Returns:
        包含两个元素的元组：数据项列表和元数据字典
    """

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f) # open the file

    if isinstance(data, dict): # dict --> return its items and meta-dict
        items = data.get("items", [])
        meta = {k: v for k, v in data.items() if k != "items"}
        return items, meta
    if isinstance(data, list):
        return data, {}
    raise ValueError(f"Unsupported json structure in {path}: {type(data)}")


def normalize_text(value: Any) -> str:
    """标准化文本，去除多余空格并将多行文本合并为单行
    
    Args:
        value: 待处理的值
        
    Returns:
        处理后的字符串
    """

    if value is None:
        return ""

    text = str(value).strip()
    return " ".join(text.split())


def normalize_questions(values: Any) -> List[str]:
    """标准化问题列表，过滤掉空值并清理每个问题文本
    
    Args:
        values: 待处理的问题列表或单个问题
        
    Returns:
        清理后的问题列表
    """

    if values is None:
        return []
    if isinstance(values, list):
        return [normalize_text(v) for v in values if normalize_text(v)]
    text = normalize_text(values) # normalize text
    return [text] if text else []


def merge_records(
    scenario_items: Iterable[Dict[str, Any]],
    answer_items: Iterable[Dict[str, Any]],
    evaluation_items: Iterable[Dict[str, Any]],
) -> List[Dict[str, Any]]:

    """合并场景、答案和评估记录到统一的数据结构中
    
    Args:
        scenario_items: 场景项目迭代器
        answer_items: 答案项目迭代器
        evaluation_items: 评估项目迭代器
        
    Returns:
        合并后的记录列表
    """

    merged: Dict[int, Dict[str, Any]] = {}

    def upsert(items: Iterable[Dict[str, Any]], source_name: str) -> None:

        """内部函数：更新或插入记录到merged字典中"""

        for raw in items:
            idx = raw.get("idx")
            if idx is None:
                raise ValueError(f"Missing idx in {source_name}: {raw}")
            record = merged.setdefault(int(idx), {"idx": int(idx), "source_files": []})
            record.update(raw)
            record["source_files"].append(source_name)

    upsert(scenario_items, "scenario")
    upsert(answer_items, "answer")
    upsert(evaluation_items, "evaluation")

    unified: List[Dict[str, Any]] = []
    for idx in sorted(merged):
        raw = merged[idx]
        score_value = raw.get("score", None)
        score = None
        if score_value is not None:
        
        try:
                score = float(score_value)
            except (TypeError, ValueError):
                score = None

        record = {
            "schema_version": SCHEMA_VERSION,
            "item_id": f"item-{idx:04d}",
            "idx": idx,
            "theme": normalize_text(raw.get("theme")),
            "original_rule": normalize_text(raw.get("original_rule")),
            "opposite_rule": normalize_text(raw.get("opposite_rule")),
            "scenario": normalize_text(raw.get("scenario")),
            "question": normalize_text(raw.get("question")),
            "critical_questions_original": normalize_questions(raw.get("critical_questions_original")),
            "critical_questions_opposite": normalize_questions(raw.get("critical_questions_opposite")),
            "answer": normalize_text(raw.get("answer")),
            "score": score,
            "reason": normalize_text(raw.get("reason")),
            "source_files": raw.get("source_files", []),
        }
        record.update(derive_labels(record))
        unified.append(record)
    return unified


def derive_labels(record: Dict[str, Any]) -> Dict[str, Any]:
    """从记录中推导出各种标签（规则对齐、分数段、难度等）
    
    Args:
        record: 输入记录
        
    Returns:
        包含各种派生标签的字典
    """

    score = record.get("score")
    rule_alignment: Optional[str] = None
    rule_choice_answer: Optional[str] = None
    score_band: Optional[str] = None
    score_band_answer: Optional[str] = None
    score_distance_from_center: Optional[float] = None

    if score is not None:
        score = max(0.0, min(1.0, float(score)))
        if score <= 0.35:
            rule_alignment = "original"
            rule_choice_answer = "A"
        elif score >= 0.65:
            rule_alignment = "opposite"
            rule_choice_answer = "B"
        else:
            rule_alignment = "balanced"
            rule_choice_answer = "C"

        if score < 0.20:
            score_band = "strong_original"
            score_band_answer = "A"
        elif score < 0.40:
            score_band = "lean_original"
            score_band_answer = "B"
        elif score < 0.60:
            score_band = "balanced"
            score_band_answer = "C"
        elif score < 0.80:
            score_band = "lean_opposite"
            score_band_answer = "D"
        else:
            score_band = "strong_opposite"
            score_band_answer = "E"
        score_distance_from_center = abs(score - 0.5)

    difficulty, difficulty_meta = estimate_difficulty(record)

    return {
        "rule_alignment": rule_alignment,
        "rule_choice_answer": rule_choice_answer,
        "score_band": score_band,
        "score_band_answer": score_band_answer,
        "score_distance_from_center": score_distance_from_center,
        "difficulty": difficulty,
        "difficulty_meta": difficulty_meta,
    }


def estimate_difficulty(record: Dict[str, Any]) -> Tuple[str, Dict[str, float]]:
    """确定性难度计算规则

    简单/中等/困难是根据三个因素计算得出的：
    1. 评分接近0.5的模糊度（越模糊=>越难）
    2. 关键问题的数量（分支越多=>越难）
    3. 情境+问题+答案的文本长度（越长=>越难） Hancy:此处待定，文本长可用信息会更多，未必更难？
    """

    score = record.get("score")
    if score is None:
        ambiguity = 0.5
    else:
        ambiguity = 1.0 - min(abs(float(score) - 0.5) / 0.5, 1.0)

    total_critical = len(record.get("critical_questions_original", [])) + len(
        record.get("critical_questions_opposite", [])
    )
    critical_score = min(max((total_critical - 4) / 4, 0.0), 1.0)

    text_length = (
        len(record.get("scenario", ""))
        + len(record.get("question", ""))
        + len(record.get("answer", ""))
    )
    text_score = min(text_length / 520.0, 1.0)
    
    # 此处的判断标准未必准确，这个版本是GPT写的，仍可进一步修改
    difficulty_score = 0.55 * ambiguity + 0.20 * critical_score + 0.25 * text_score

    if difficulty_score < 0.34:
        difficulty = "easy"
    elif difficulty_score < 0.56:
        difficulty = "medium"
    else:
        difficulty = "hard"

    return difficulty, {
        "difficulty_score": round(difficulty_score, 4),
        "ambiguity_score": round(ambiguity, 4),
        "critical_score": round(critical_score, 4),
        "text_score": round(text_score, 4),
        "text_length": text_length,
        "total_critical_questions": total_critical,
    }


def build_rule_choice_mqa(record: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """构建规则选择MQA任务的数据格式
    
    Args:
        record: 输入记录
        
    Returns:
        格式化的规则选择MQA数据，如果没有有效答案则返回None
    """

    if not record.get("rule_choice_answer"):
        return None

    stem = (
        f"请判断下面回答在该情境下更接近哪种规则立场。\n\n"
        f"主题：{record['theme']}\n"
        f"情境：{record['scenario']}\n"
        f"问题：{record['question']}\n"
        f"参考回答：{record['answer']}"
    )
    choices = [
        {"id": "A", "text": f"更接近 original_rule：{record['original_rule']}"},
        {"id": "B", "text": f"更接近 opposite_rule：{record['opposite_rule']}"},
        {"id": "C", "text": "需要在 original_rule 与 opposite_rule 之间做条件性权衡，不能绝对套用任一条规则。"},
        {"id": "D", "text": "仅根据当前信息仍无法判断回答的立场。"},
    ]
    return {
        "schema_version": SCHEMA_VERSION,
        "task_type": "rule_choice",
        "mqa_id": f"rule-choice-{record['idx']:04d}",
        "source_item_id": record["item_id"],
        "difficulty": record["difficulty"],
        "score": record["score"],
        "rule_alignment": record["rule_alignment"],
        "prompt": stem,
        "choices": choices,
        "answer": record["rule_choice_answer"],
        "metadata": {
            "theme": record["theme"],
            "question": record["question"],
            "original_rule": record["original_rule"],
            "opposite_rule": record["opposite_rule"],
            "critical_questions_original": record["critical_questions_original"],
            "critical_questions_opposite": record["critical_questions_opposite"],
        },
    }


def build_score_band_mqa(record: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """构建分数段MQA任务的数据格式
    
    Args:
        record: 输入记录
        
    Returns:
        格式化的分数段MQA数据，如果没有有效答案则返回None
    """
    if not record.get("score_band_answer"):
        return None

    stem = (
        f"请判断下面回答在 0-1 的规则立场分数落在哪个区间。\n"
        f"分数越接近 0 表示越接近 original_rule，越接近 1 表示越接近 opposite_rule。\n\n"
        f"主题：{record['theme']}\n"
        f"original_rule：{record['original_rule']}\n"
        f"opposite_rule：{record['opposite_rule']}\n"
        f"情境：{record['scenario']}\n"
        f"问题：{record['question']}\n"
        f"参考回答：{record['answer']}"
    )
    choices = [
        {"id": "A", "text": "[0.00, 0.20) 强 original"},
        {"id": "B", "text": "[0.20, 0.40) 偏 original"},
        {"id": "C", "text": "[0.40, 0.60) 中间/平衡"},
        {"id": "D", "text": "[0.60, 0.80) 偏 opposite"},
        {"id": "E", "text": "[0.80, 1.00] 强 opposite"},
    ]
    return {
        "schema_version": SCHEMA_VERSION,
        "task_type": "score_band",
        "mqa_id": f"score-band-{record['idx']:04d}",
        "source_item_id": record["item_id"],
        "difficulty": record["difficulty"],
        "score": record["score"],
        "score_band": record["score_band"],
        "prompt": stem,
        "choices": choices,
        "answer": record["score_band_answer"],
        "metadata": {
            "theme": record["theme"],
            "reason": record["reason"],
            "question": record["question"],
        },
    }


def write_jsonl(path: Path, rows: Iterable[Dict[str, Any]]) -> int:
    """将数据行写入JSONL文件
    
    Args:
        path: 输出文件路径
        rows: 要写入的数据行
        
    Returns:
        写入的行数
    """

    count = 0
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
            count += 1
    return count


def write_difficulty_splits(task_rows: List[Dict[str, Any]], task_name: str, output_dir: Path) -> Dict[str, int]:
    """按难度级别分割任务数据并写入不同文件
    
    Args:
        task_rows: 任务数据行列表
        task_name: 任务名称
        output_dir: 输出目录
        
    Returns:
        每个难度级别的计数字典
    """

    task_dir = output_dir / task_name
    task_dir.mkdir(parents=True, exist_ok=True)
    counts: Dict[str, int] = {}
    for level in ["easy", "medium", "hard"]:
        rows = [row for row in task_rows if row.get("difficulty") == level]
        counts[level] = write_jsonl(task_dir / f"{task_name}_{level}.jsonl", rows)
    return counts


def build_manifest(
    unified_rows: List[Dict[str, Any]],
    rule_rows: List[Dict[str, Any]],
    score_rows: List[Dict[str, Any]],
    args: argparse.Namespace,
) -> Dict[str, Any]:
    """构建数据集清单文件，包含统计数据和元数据
    
    Args:
        unified_rows: 统一数据行列表
        rule_rows: 规则选择任务数据行列表
        score_rows: 分数段任务数据行列表
        args: 命令行参数
        
    Returns:
        清单数据字典
    """

    unified_difficulty = Counter(row["difficulty"] for row in unified_rows)
    rule_difficulty = Counter(row["difficulty"] for row in rule_rows)
    score_difficulty = Counter(row["difficulty"] for row in score_rows)
    themes = Counter(row["theme"] for row in unified_rows)
    rule_alignment = Counter(row.get("rule_alignment") for row in unified_rows if row.get("rule_alignment"))
    score_bands = Counter(row.get("score_band") for row in unified_rows if row.get("score_band"))

    return {
        "schema_version": SCHEMA_VERSION,
        "inputs": {
            "scenario_json": str(args.scenario_json),
            "answer_json": str(args.answer_json),
            "evaluation_json": str(args.evaluation_json),
        },
        "difficulty_rules": {
            "easy": "difficulty_score < 0.34",
            "medium": "0.34 <= difficulty_score < 0.56",
            "hard": "difficulty_score >= 0.56",
            "difficulty_score_formula": "0.55 * ambiguity + 0.20 * critical_score + 0.25 * text_score",
            "ambiguity": "1 - abs(score - 0.5) / 0.5; closer to 0.5 => harder",
            "critical_score": "normalized count of critical questions from both rule sides",
            "text_score": "normalized length of scenario + question + answer",
        },
        "rule_choice_label_rules": {
            "A": "score <= 0.35 => closer to original_rule",
            "B": "score >= 0.65 => closer to opposite_rule",
            "C": "0.35 < score < 0.65 => balanced/conditional tradeoff",
            "D": "reserved distractor; never used as gold label in current data",
        },
        "score_band_label_rules": {
            "A": "[0.00, 0.20)",
            "B": "[0.20, 0.40)",
            "C": "[0.40, 0.60)",
            "D": "[0.60, 0.80)",
            "E": "[0.80, 1.00]",
        },
        "counts": {
            "unified_intermediate": len(unified_rows),
            "rule_choice_mqa": len(rule_rows),
            "score_band_mqa": len(score_rows),
        },
        "difficulty_distribution": {
            "unified": dict(unified_difficulty),
            "rule_choice": dict(rule_difficulty),
            "score_band": dict(score_difficulty),
        },
        "theme_distribution": dict(themes),
        "rule_alignment_distribution": dict(rule_alignment),
        "score_band_distribution": dict(score_bands),
    }


def parse_args() -> argparse.Namespace:
    """解析命令行参数
    
    Returns:
        解析后的参数命名空间对象
    """

    parser = argparse.ArgumentParser(description="Build intermediate JSONL and MQA datasets from scenario/answer/evaluation json files.")
    parser.add_argument("--scenario_json", type=str, required=True, help="Path to scenario.json")
    parser.add_argument("--answer_json", type=str, required=True, help="Path to answer.json")
    parser.add_argument("--evaluation_json", type=str, required=True, help="Path to evaluation.json")
    parser.add_argument("--output_dir", type=str, required=True, help="Output directory for jsonl artifacts")
    return parser.parse_args()


def main() -> None:
    """主函数，执行数据集构建流程"""
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    scenario_items, scenario_meta = load_items(args.scenario_json)
    answer_items, answer_meta = load_items(args.answer_json)
    evaluation_items, evaluation_meta = load_items(args.evaluation_json)

    unified_rows = merge_records(scenario_items, answer_items, evaluation_items)
    rule_rows = [row for row in (build_rule_choice_mqa(r) for r in unified_rows) if row]
    score_rows = [row for row in (build_score_band_mqa(r) for r in unified_rows) if row]

    write_jsonl(output_dir / "unified_intermediate.jsonl", unified_rows)
    write_jsonl(output_dir / "mqa_rule_choice.jsonl", rule_rows)
    write_jsonl(output_dir / "mqa_score_band.jsonl", score_rows)
    write_difficulty_splits(rule_rows, "rule_choice", output_dir)
    write_difficulty_splits(score_rows, "score_band", output_dir)

    manifest = build_manifest(unified_rows, rule_rows, score_rows, args)
    manifest["source_meta"] = {
        "scenario_meta": scenario_meta,
        "answer_meta": answer_meta,
        "evaluation_meta": evaluation_meta,
    }
    with open(output_dir / "manifest.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)

    print(json.dumps({
        "output_dir": str(output_dir),
        "unified_intermediate": len(unified_rows),
        "rule_choice_mqa": len(rule_rows),
        "score_band_mqa": len(score_rows),
        "difficulty_distribution": manifest["difficulty_distribution"],
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
